# Generated by Django 5.0.6 on 2024-06-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('is_linked_with_zohocrm', models.BooleanField(default=False)),
                ('zcrm_product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('purchase_account_id', models.CharField(max_length=50)),
                ('purchase_account_name', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('purchase_description', models.TextField()),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_type', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=20)),
                ('stock_on_hand', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_attachment', models.BooleanField(default=False)),
                ('available_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actual_available_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sku', models.CharField(max_length=50)),
                ('reorder_level', models.CharField(blank=True, max_length=50, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_type', models.CharField(blank=True, max_length=50, null=True)),
                ('image_document_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField()),
                ('last_modified_time', models.DateTimeField()),
                ('cf_qb_ref_id', models.CharField(max_length=50)),
                ('cf_qb_ref_id_unformatted', models.CharField(max_length=50)),
            ],
        ),
    ]
