# Generated by Django 5.0.6 on 2024-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_items', '0003_alter_zohoitem_description_alter_zohoitem_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
