# Generated by Django 5.0.6 on 2025-09-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_items', '0004_zohoitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoitem',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
