# Generated by Django 5.0.6 on 2024-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('language_code_formatted', models.CharField(blank=True, max_length=10)),
                ('contact_type', models.CharField(max_length=50)),
                ('contact_type_formatted', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('customer_sub_type', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('is_linked_with_zohocrm', models.BooleanField(default=False)),
                ('payment_terms', models.IntegerField()),
                ('payment_terms_label', models.CharField(max_length=50)),
                ('currency_id', models.CharField(max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('currency_code', models.CharField(max_length=10)),
                ('outstanding_receivable_amount', models.FloatField()),
                ('outstanding_receivable_amount_bcy', models.FloatField()),
                ('outstanding_payable_amount', models.FloatField()),
                ('outstanding_payable_amount_bcy', models.FloatField()),
                ('unused_credits_receivable_amount', models.FloatField()),
                ('unused_credits_receivable_amount_bcy', models.FloatField()),
                ('unused_credits_payable_amount', models.FloatField()),
                ('unused_credits_payable_amount_bcy', models.FloatField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('portal_status', models.CharField(max_length=50)),
                ('portal_status_formatted', models.CharField(max_length=50)),
                ('track_1099', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField()),
                ('created_time_formatted', models.CharField(max_length=50)),
                ('last_modified_time', models.DateTimeField()),
                ('last_modified_time_formatted', models.CharField(max_length=50)),
                ('ach_supported', models.BooleanField(default=False)),
                ('has_attachment', models.BooleanField(default=False)),
            ],
        ),
    ]
