services:
  backend-app:
    build:
      context: ./api_qbwc_zoho_backend
      dockerfile: Dockerfile
    container_name: backend-app
    volumes:
      - ./api_qbwc_zoho_backend:/app
      - ./api_qbwc_zoho_backend/_gunicorn/gunicorn.conf.py:/etc/nginx/gunicorn.conf.py
      - ./api_qbwc_zoho_backend/local_backup:/app/backup
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project_api.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
      - LOGINUSER_USERNAME=test
      - LOGINUSER_EMAIL=test@example.com
      - LOGINUSER_PASSWORD=Hialeah2024*-
      - CELERY_BROKER_URL=redis://redis-installation:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-installation:6379/0
    env_file:
      - ./api_qbwc_zoho_backend/.env
    networks:
      - shared-network
    restart: unless-stopped
    depends_on:
      - redis-installation

  # react-app:
  #   build:
  #     context: ./api_qbwc_zoho_frontend
  #     dockerfile: Dockerfile.onpremise
  #   container_name: react-app
  #   volumes:
  #     - ./api_qbwc_zoho_frontend/build:/app/build 
  #   env_file:
  #     - ./api_qbwc_zoho_frontend/.env
  #   restart: unless-stopped
  #   networks:
  #     - shared-network

  postgres-server:
    image: postgres:16.0
    container_name: postgres-server
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./api_qbwc_zoho_backend/scripts_db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=api_qbwc_zoho_envqa_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - shared-network

  nginx-server:
    build:
      dockerfile: nginx_onpremise/Dockerfile
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend-app
      # - react-app
    restart: unless-stopped
    networks:
      - shared-network

  redis-installation:
    image: redis:latest
    container_name: redis-installation
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  postgres-data:
  redis-data:

networks:
  shared-network:
    external: true
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: "10.1.10.0/24"