apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml -o .\k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: django-app
  name: django-app
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: django-app
