apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml -o .\k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: django-app
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml -o .\k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: django-app
    spec:
      containers:
        - env:
            - name: DB_ENGINE
              valueFrom:
                configMapKeyRef:
                  key: DB_ENGINE
                  name: django-app-env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: django-app-env
            - name: DB_NAME_DEV
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME_DEV
                  name: django-app-env
            - name: DB_NAME_PROD
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME_PROD
                  name: django-app-env
            - name: DB_NAME_QA
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME_QA
                  name: django-app-env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: django-app-env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: django-app-env
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: django-app-env
            - name: DJANGO_SETTINGS_MODULE
              value: project_api.settings
            - name: DJANGO_SUPERUSER_EMAIL
              value: admin@example.com
            - name: DJANGO_SUPERUSER_PASSWORD
              value: admin
            - name: DJANGO_SUPERUSER_USERNAME
              value: admin
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  key: FRONTEND_URL
                  name: django-app-env
            - name: LOGINUSER_EMAIL
              value: test@example.com
            - name: LOGINUSER_PASSWORD
              value: Hialeah2024*-
            - name: LOGINUSER_USERNAME
              value: test
            - name: SALES_TAX_LIST_ID
              valueFrom:
                configMapKeyRef:
                  key: SALES_TAX_LIST_ID
                  name: django-app-env
            - name: ZOHO_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  key: ZOHO_AUTH_URL
                  name: django-app-env
            - name: ZOHO_SCOPE_CUSTOMERS
              valueFrom:
                configMapKeyRef:
                  key: ZOHO_SCOPE_CUSTOMERS
                  name: django-app-env
            - name: ZOHO_SCOPE_INVOICES
              valueFrom:
                configMapKeyRef:
                  key: ZOHO_SCOPE_INVOICES
                  name: django-app-env
            - name: ZOHO_SCOPE_ITEMS
              valueFrom:
                configMapKeyRef:
                  key: ZOHO_SCOPE_ITEMS
                  name: django-app-env
            - name: ZOHO_TOKEN_URL
              valueFrom:
                configMapKeyRef:
                  key: ZOHO_TOKEN_URL
                  name: django-app-env
            - name: ZOHO_URL_READ_CUSTOMERS
              valueFrom:
                configMapKeyRef:
                  key: ZOHO_URL_READ_CUSTOMERS
                  name: django-app-env
            - name: ZOHO_URL_READ_INVOICES
              valueFrom:
                configMapKeyRef:
                  key: ZOHO_URL_READ_INVOICES
                  name: django-app-env
            - name: ZOHO_URL_READ_ITEMS
              valueFrom:
                configMapKeyRef:
                  key: ZOHO_URL_READ_ITEMS
                  name: django-app-env
          image: django-app
          name: django-app
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/gunicorn.conf.py
              name: django-app-cm1
              subPath: gunicorn.conf.py
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: gunicorn.conf.py
                path: gunicorn.conf.py
            name: django-app-cm1
          name: django-app-cm1
