apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml -o .\k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml -o .\k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx-server
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-cm0
              readOnly: true
              subPath: nginx.conf
            - mountPath: /etc/nginx/certificates
              name: nginx-cm1
              readOnly: true
            - mountPath: /usr/share/nginx/html
              name: nginx-cm2
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx_react_django.conf
                path: nginx.conf
            name: nginx-cm0
          name: nginx-cm0
        - configMap:
            name: nginx-cm1
          name: nginx-cm1
        - configMap:
            name: nginx-cm2
          name: nginx-cm2
