apiVersion: v1
binaryData:
  api-qbwc-zoho.pfx: TUlJUnR3SUJBekNDRVdVR0NTcUdTSWIzRFFFSEFhQ0NFVllFZ2hGU01JSVJUakNDQzdvR0NTcUdTSWIzRFFFSEJxQ0NDNnN3Z2d1bkFnRUFNSUlMb0FZSktvWklodmNOQVFjQk1GOEdDU3FHU0liM0RRRUZEVEJTTURFR0NTcUdTSWIzRFFFRkREQWtCQkRoamJmeEdYcFExVGM4S2IzNTc1TTVBZ0lJQURBTUJnZ3Foa2lHOXcwQ0NRVUFNQjBHQ1dDR1NBRmxBd1FCS2dRUXZ0NlR2Q205d2NRSWtoTHhkd0xub1lDQ0N6Q2pYNzJ3MHlXOUJRTnRRODVIM3RIYWZOSVNmT043Nlk1SFZ0bDFmZlN2VjRkVkVMNUhyM0tjOEhtSzBOS3lEZVkrbjBtaDFtNnRRSHRqQVNkU04xRVVZSjRYRmRUY2kzdHdtMFE2NG80UTdmenptTDJEV09ETkJCbUI4eDE2OHdKNWt1dmdZMVZsVy9ySEdhT1hQN1dLbXpHL05RMnlaVndtWmlRU2xkb0YrRGxkUnBXQ3JBRHhhN1lJaFdGTlIwNkhjSysyVmtBYVZucE9pNU0zbHZTM1dmZGttc09Vd0J6TDFKeVJHWTh0dVp6bEVoYk9YQlduYVdxM2N0bDNLQUl2ekZQMWFrdEtORDl1bU52RFNBeFJUNEpPVm10RTljRjEvNWJPa08yaUlHYnArYjVidWxqbTJ3YkF2RkxCQ0xJeUVRWVVISGVEZ3BCUm01ejVZUG9YeEVBVHNIL05WZ2FSeVRTNDMzTld5VU1HdzZ0SXRoRklhWExNQlcrYU9hUW1OVlRKSVB6MnBGM2xiYVNQUnpkOWs3bHV6OFI0T1BqVUJua1lBbXNVaUVybnpjamY1d3Y1NitLQWptME9wbGtxV0lNeWEzWmFoMXkzVjYrZnM5aGpKZnAyTUk3T2traXFQTkMxV0xKVkhUL0FRUFA4TzdXM1A4cnBSRVI5SjhFOUpiSGlZQ3VEK2dqejRrZDRqaXlpQkZFMUFTU0lqMjJPLyt6VjMwMmNudWo3aFh3ZzZLd1Q1V3hnL1BreUxDcFRSbzhGeEo2czRSRXc1WjFVN2JseEdGSjA0dmhnYllxSVVYZnRlRmxXVEhvQWhZYm1LLy8xMERLcE1kYlIvRlZQaVh3ODdjRzEyaHAzTVU5cG92RlhPK0NMV21FcVU5bWRtWklCRjdrdHEybVJEaGFEcjFEY09VeU5TSkJQbG94bVVLenhycXY4NU5pUmw5SFRYVFlzZzBHMkZRRXMwN0xqem13YldHSDArRXhaeU42ZHJ5UmYvSnBaODFra01WbjAvUEhqRWtHeFdWQVFkK1pJLzhTM3FQNEV1M3BLcnBYaFJXdFZ4QXk3TkpCbVkrUTRQMnZFYWZ1RzRRd1psZndGM1p5TVJWdDMvZ3JEcW0vWkJiYk1mQ0hrNldTY1BNWkhOSUNjNVE3UUJsblMxWUpOeDg3bWRZUTBhOTlwZ0xMYTAxRTZhMDhYWGZ4ZUZGUHlHNEJGZWwxOEw4WWFMUm1OWUxNMWtCbWV5dy9uVjRGUWFRcGZxZFNIVlZvZjZENkl3eFI3bmFaVDBPMk5SWlFVdjg2TlFndWpDRnRmRVVqdXJ6aVcxQlJwNGN5MUJGUjhOUm1vaVQyeDFsZVRzT0lrejNlMGh0QmhkWHh5ZGsxYUd1eDR4bHpMYVUwV3B1NXNFV2k3c1lndVdlb05PL0h0ZUZwNGtNdHJ0b3c1V1ZpUS8zaFZsUHArQ1dpZGdUN3pDTGxIamRwZlg0K01Zb080NlJEZVR6TlluK1RnclBpOG8zWlc3YU9EQzNNa3MrSXNJalk0ZkxsMThaeWZKUkJ1dFRycE1UYlBXdGJpcnJuTDhTL1JxNlpXRkRtTEorZVVCSmdhemQyMnl1UEhYbkJiTGs0MGJGSEorUU9QSEptTWUvdElSbG5PQTJZYlB0S2NocTE0SEZsbmdvS0RRR2NpeTdUQ0p1aE53YXBYenFnZUJYd0xkQkhMcHpNcFpqRk1JekRjUjN0UnM3bWZJNUowRUtiZnZKREFGMlEvN3QrMEd0a3p4WjMxWVpUVXRUU0RQV3Jia2FWdHBOREFNNTJiTTQwdmFFTHZIR2dzYUhIZkVZMXY3OHR0dlYxSW5QNEV1UzRQd0xMMjZuQWpIcWcraVNHNGFXdXNmZUNNa0Fpb1lmTkNSS1pZRnlsd1I1QzVKUGdNOEJRMXdsSkNxY01oMFp6MmI5VU1qK2xzQ1lPQ2JzTTgyb0lsNFNrdXVzQ1EyTFhGRGpjUUdNbHUyNVFQdEFvVHlScG1BV280ekxPRVF1V3ZSbGEycmRYSjcxV21Fa1ltaFpMQStaMHJCWlMwZEk0SUc3Y09vT0hNTGI0d3FaMFpqSndkSUJBUkJvak9RNjdKQjIxa3VGZVgybGpkNjRBSzk3YkpMU25HZTJTMWZUanFhNTVTYXBLT3pPYUZEektCTGVkcUpyWDU4Um1ZK3kvdEhJRGFUS1JGU2kwYnVNWWFnUCt4ZDd4MVBjQ0kwTDdKWHg5Y3JMNnk1bmpLLzd6TmVZcTJNS2wxVm9QVnF5T2xHTzBoNVd1UHRIS0x0NG9raS8xeXg5MUFVRUdWdWZEVEg5ZkdJZnFlZXhvaVhVeDZ3Z3E3QmNBZFZXaUxPUVBpNlpaL2dISVZJby9wUG1UU3VHTlpxbk9idUozeVpDYU9CNXQ1bWp0eHNBcDQ2RWJPVkJUTlhmcFl5cjFlN296WEQza0JNWGJNV3pZT0g2OXNpN0h5YUZiTDhVMW1wSTRWOS94RnRwMlROQURMOFBJYmtxM2NvcDJpLzdTcVdta2k4ZEFMT0Y3MDQ2T3NRUVNXdDliTHUrY3o2amUwZzUwY3FHZTFyamVpaVJyUGdmcERoVmJKdXBKMzVtT1VGalJ1bEY2WndONm9YNlZld0M1UENtRStrcE9GYzVBQmRCeEJkc2FPVVpsRXAyamw3dkVqSFRTOWVsa2xabW9PVk93K1kvUkczWkFHbkx0OGR4YklWMGtWbTJ0SCt4eVc4VTdQWmhLY0VvdzBTUjFkM3ZmTjJ4T2Y0a0FXSVdrSGpGQnNjQURMaFROTno1WnczRC9KL2gvNmM4Wm5aOU9XUUExUVhVdGFUMGFmUUlvTThJVWhzVzU2TnJTNjN5VWIrc1FzN3A1TlU2Z0dOeVkwS0lJaFZ0R2RjWm05dlhyTHhyakN1bkRJNUI4ZXlYcXZqZVZnQWlJU2JKd1JOZXY3ZUhJWStyMEtjSVE3VDY3Q0ZXRE8wMWc2R09lN3JzUzFFUFpYRGhYNDZjNzMrWG4xN2RzZHdEaEJaRWhzeGVwRVFGRTlGRHBOQnVoRFhxMy9UeEYrNCtlQVhuOUlNVUNUeWNMSkY2QjdBTjVsWTl2WXRsbjZqMURWVU9XZnFicHpQVVl4dy9TN2FJRGxwQkI4UmxWVjRlVkdNV3pJMHd6aU5GYlNQK2dyNzdGaGFYM1NqR1owQ0pRYndlMEJyUnJ1R3FZWDNoUG0wWnlqMjFqaytEZFJMMFExUHVQN0R5VzhPY1IyU3hYV1FlY1ExeEJxaWpneStISE9zWTFLZ00zOGJoZlBmNGxKUjRCa1pMVjNYUmJxc0VpWXlXLzdRZkJtUE92bFFPNE1tblgzQlhBdU9jRTQ1Mml4VktLeUtHNGxJbCswOEVha3lJUnc3NG1RRTFuWkhWL2FxWStZWUVnWngxOTdjUW9zMTlrVDFwbWNrZnFtZGtXUFY0VVA4eko3YjNic3FUUjcyRVk3TlM2c3RNeWk3ZXFCalFIZkdPUU9wSnJvQnN1eUhqM2VZSFl4WW1wcGI1NXJZeUcvQ2V2N3dTNGpCN05vRUIrN2VISkoycDRNL2hiaTBGYW5zYjZmRTBYbjRSS3NzS1BGN1RFOCtQRXdhV1pqeUFUbnNhZUY3cFJMYjB5KzVEZ2JvbGtxQjVzNlBYdVhPKzdkNFYrcnZXTHNsdjNVd3VjeCtFSStXVzRCRFBOY3N3OG1yREdmU3I2ZEdBeVp3RTRFdWNvWG4xeWh1VXdyTlNKcVVzekYwbUordW8weGErVUdDNkNVL0R1WTZmODI0a0hiKytQWHkwQWNMTDZLYUkyM3dzeGNqZkkrdUh1NTAxd1FrZk4yZkxhSDRKT2MwRzVwNFpiakZubWZ3NmZhTEs1YkVCd29iVVFvOUh0dklZQytpRkp3V1BGUVJ4S3lWTlZrSmFzZ0NmK0xkcCtwUlY0dDViS1lwVWZJWHdhdEFZQnNSeG5UMFllR2cwTW1scTZtdnNBK3ZlL1c2bStSdUJHTCs4NnpURkVOUFI2Y1VmZTA3Q0Nldk5uNmROWGhSdXpIUG1OUmlRanpadUxYWFphMTZoNStNcmFudDBNeWNvQVJVdXRLZW9wcWlmQkpEaUMvanNKQmhpcW9mdHZPa0ozaFJ5WjkwNkJscWd3cTBzLzFrU0luaXc3WkJtakNPSkRpcmtUS3VxUlo1aklOWjdqYU56QkYxUy9xR1pwMys5a1czWmVENGZuelZTNnZaVHd0cEJBN0dKYzlpbWhyQXRrVEw1RDl4TTdZcVlzUitYOXp4RmxWQnQwQzNlVFFQK3M5eWs0ZU9jZFlJNlNZN0xUWk9BY0VLRllTTXdPcDQ5UVUvUFFCWm82ekg5MUgwWEdGZnIxcVRsS2d2SnpaWU1MVVAyd0tHYWYya2hKdGRTYVVrVWtJcDJKYWtpSHZoVkRCdk42RlZqTGh6aXhhV0U0eUQ3NDNLT1JiZ3NJTHhmM1o0dlRIV1RaTVd5ZXp3Qm0rbXpLTWYyNGhRQWdUMmhROVl5TkZ2eGtIdExwekdlK2pncUVNNU93dnZ0THQ3MXlxYXlCeEc0eWpLYTUzdlFqMm5LY3Y5cVZyZzRQbXluakU0a3FvQ2JjQkFtV1VPWU1pNXhhd3hFY1U1QmVrSWtjSWRhNkxlYk1hV0RtdFRkUlcxcWRoS3JlbmordEFSdjVwTU9RR3NTb1loMTlDTi8yZS9hejI5UWtLaW14ckk3Q1NjOURrSnZQbnNxL05uN09pUGxtVnBVYUZ1NmFrOURwYXkvZEo2NmtrYWlNSHZmaWFsNmdMVFFYZXdKdkZKQlFRVUJJbXlLSFFsWnpjRjhTTGNONCtKb0RheWpvREYvWldZVytrT0ZlU2JvQVdST1ZibnJxc3ovZm40V1ZjbC9NMXJZZmZCeGpXZnBMYWhxZGRHVm9ONVRGLzV3WGFHRWg5a25OVVVHU0IwMXl1SzU5eHAwOHhZQkNKVkhWZlk5OGU0TzBldzhVb0U0RzN3OXRZbnJCbk5sUC9TRitlbENzd2dDK0tsdDhlbi9mS0Vnd05oV0drTHBEa2N2MGxhRENDQll3R0NTcUdTSWIzRFFFSEFhQ0NCWDBFZ2dWNU1JSUZkVENDQlhFR0N5cUdTSWIzRFFFTUNnRUNvSUlGT1RDQ0JUVXdYd1lKS29aSWh2Y05BUVVOTUZJd01RWUpLb1pJaHZjTkFRVU1NQ1FFRU9ub0EwQTI4dCtvVWdFVGZEMVlkN1FDQWdnQU1Bd0dDQ3FHU0liM0RRSUpCUUF3SFFZSllJWklBV1VEQkFFcUJCRGRSU0Zpd3FYdzFPSzRncHdzZjQ3Y0JJSUUwR24zK3NBV2tlbis1Y3NkNFNsajNzWTZmWHNWb3RUaWJxelF1Y1hJQkJuU000RVlsS0gyRmdmKy9Kc0NZb3d2SnlibThMUVZDeXRFVXlINGwxSHR3NkN2MzMrNkh6RGV3UjNXbDArOGEvMkdLT3k5MThzSHZJQXhPSlhjVGt1ZmxIMmZzUkJUc2JJVFhjNXdHWTNPLzdpQ2ZhVHBOQ29MODJCeWtDU09QNUFPR0xPdzQ4cHcyMFcrUDB4YnRsRnlOVWUvUXpwbGVTRERkYlVIbkNZRUg1dy9PN0J4TnFkT0NnMUFUSGxKdDI2NDJIb3ZQdVdXMmRvcUx2VTdFR1JOVUxvaEZOL0pTTktrKzEyTnl2T3RJMlc1SFR6aEJwZU9Xdk5NcnFwdTFvcGwyV3pheEUvb3hKcjFZVjU4VVUzUGFXSW1FWmkyMzBOSWhoOTNNRHlGSTYvUVp4eHpReGdaQXl2NnovTUthTkhjNy9RTWRjVzNnZzRCZkdnc2I2NmpCS3VWY1lNaS9UbUd4WHIxVitYRCs4cG0yVmNkR1hCYzg5RHBOenplbnNtOFNNOHRqL2swMSs3Z0V2Y29ERDZNaUczb3V5U1BETnpoTGFtUFdaTEdHZFVHK2NBNU1YWE5Kd0JldHBobGVvZU0rbGRrQTBsdWxvK3JwTTV6a0lTU1lURGtTdkRlL3lQcW1hNVAxQy9GSFBpR1NVN3JPRXdKZEtuSGh3M0UxWDlIYkJuc1djbUJvcDFETkVibUtpY1BaWGhqV0prZHhKa1JhanIyZVlLY3JrMkY3T0R3Znh6aWw0dHpRZXAwSUhJSndoVGpKYnFRNXFURTMrWXJSNHQxK3JveXlCUkMveTZmRGdQc2w2b1RTNFlXYVNSUDQ3aTQvM0U4YXJaVWthaTFhY0I3dUFsSk5rTFpGL3pob2lsSktRVXR1cStTbmxTbjZ0c1QwNVVyZnZ1Z1NYTktoTWxoMHhUQURsUmZKeUxqNHZWanluMHJsbGt5K0xBM2xpdG84OGthUkZsSzVRY0tBZFJIUm1iOFd3bVpOWTh6Tk02QTIxWW1rUndkdHVDOTRNNmlwWTQwVVdGNXlDZ21pSTlvNzlQRkVLK3dpK2dJMkhZd1dvRktTWWV2NUF4allNTm0vc0dESDBpV1VnOWVyVkEwRXBZQnBYYXdSeHB4OHJHUWhCUWFhMERYd0kxSUxHV2RUWmRNdnZUNE5yQzEvRTRWWlRtR2V0bFNPWnFYdzluaVJ4Ujc4cUo2aS9wSWZqbllmLyszdUFTL2lHc2g2ZW5kZm1oV25aaDdFaVdIMFpRS3ZUS0sxOWZ3a3UxaGluMGwyV21zYm93UXpUY3kxbi9sQXNmc2ZkMnpWdTlBcDNsTW5GdGY5Z04yQ2wyQmFVWG1KV0cwQS84bzhLUnhMOXRsMHpBTTBkMXYzZUNqbDFJb29mM2w2dHlyaXp0Sk1qcDA3aXJxbWhubzVxSU1penJWMVp1ZmE0akdhSERQVVBXQnEzcmRhaVpqdHI0TVNndWwwWFlTUE1TRG5oWXREMHBXSHJtUmVNMkZoVXlITWxGRmgxMHZOM3J4UCtxM2JsdDRJcTVkajdyUWpob1VmZXpkSnF0cEJIZnU5QXhpcm14SHZqd3ZGcDhReWZPdU9TV1FXMHF5QVpnWUJ5ekRXbUtLOElaL3p3ZEVYRDgza2tvT0Vtc3hJS1VIOUk4TCtvaUlTblZaVGRDV3ZHb0U4OTd3aVJLY2w4YUhOc2haT3hMVzErT0F0WVdyaEU1Y2tvaHFVNFBybG90dGVtQkJVb1RWTktLNWJ3dWFpTHZvUmJTM05KUE01cDNxd1JOS1djTG00clNlU0JpWDRoTWkvNmNRb3pvUlF4bncxWmQvaTZiOTBXeWNoZEZWazFpZjdTbVhPRFU5QmhtWTd4aUxLU2lKU21HY0xtaFBMRkppdmZFdE1PWW1IemUxKzhRYk5GYktSY1RPSDZCVWVCZnowZWZHZWtvM1Naems1SkxRQS9UMUE4amdraGVQMjlyZlZtUlhWS3lVWVBYSUFpWTVJMVlUeVJ2VStncEZEUVpMaW94SStYVUN1dmNMbVNqZXlHVWVZaWFzeUI4SWVmR2oxMVpBWE9IcnRzL2tvR0YzcUx5MnFKakhoaFpRREZKZG54ZUZuTUdDMWxSbUp0YUVNU1V3SXdZSktvWklodmNOQVFrVk1SWUVGS2NVeW90cEd3OThvZHdwQTV1V2JXcmlYeUZBTUVrd01UQU5CZ2xnaGtnQlpRTUVBZ0VGQUFRZ1NHd1k0SWkvcms4b09QZ1p3NHBIUzhiZGVXR0VlenlUNW96WVdrZVdsdk1FRVBGZkFhYmw0bkdJVkhCaUlJK2pJSDhDQWdnQQ==
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFpTCCA42gAwIBAgIUFFynLgfuxvuhM8CVSz5rL4faTzIwDQYJKoZIhvcNAQEL
    BQAwYjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkZMMRAwDgYDVQQHDAdIaWFsZWFo
    MRowGAYDVQQKDBFOZXcgV2luZG93IFN5c3RlbTEYMBYGA1UEAwwPTldTLUludGVy
    bmFsLUNBMB4XDTI1MTIxNTIwNDMxOFoXDTM1MTIxMzIwNDMxOFowYjELMAkGA1UE
    BhMCVVMxCzAJBgNVBAgMAkZMMRAwDgYDVQQHDAdIaWFsZWFoMRowGAYDVQQKDBFO
    ZXcgV2luZG93IFN5c3RlbTEYMBYGA1UEAwwPTldTLUludGVybmFsLUNBMIICIjAN
    BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtT9+Lz2RNBqenPYOusXxtKIeMIrN
    x+wJV5Pb4BI4QVuuRz+RdZS7mE4ZY202YRDpYtp+xJ5aOddVSluqRP5OxKcc5sYf
    KuWwyKMNw7kgxyt0FgcjU2SovJ8GJP2hU/ei/VuKeY8H8pR/y0FHalExsGyAOJvf
    BpRAo/3fOsNS04xkg19pCdb5e74g1VDJUf4GASETmzveN71d4biWcJa2suBUreVk
    clNJdEcwrZVDlmIhy6P8tH9OYY5xyt8KuvxjMsxAaQXFBz3eJPV6IBKH1j9q7bmU
    Ig4zqGJyLdWbYntFiirCT1OWnmQy4qsOigkd6eCZkMYdL1q+cve140lORNns2bZf
    i2xdo0yq70zdrVftnJI07zLroBELi2hBEmkcB6QHs0ar2ivl9w2ixHB9TptZnI0N
    zdvMGGsAHynsE6o0WOYi/l4e7R6vH+Nd0a4mF3486OOw0+ok4rjCxLHPFC0pitVa
    ITlV9MUBeVlWJoqeiqBsWNmzYBdUHU/bEsQH00C7QzSQ0HvBowa9AN1qaL3Wj4Lx
    xU9MOsI0bQhbqdZ00JruNeHp8vxE0RsvTRguXUWJ7+ekpavibTw7Ogw0H2U+VpzX
    zi6LQihdcmC655PHQLpUqvIgS6NA6ncVmxZN92JMlsU+6jauKcP+uLde5LraFm06
    gD1QiRdg7mtsnPcCAwEAAaNTMFEwHQYDVR0OBBYEFJD396jTnyFbmp0n52788T8O
    R9DfMB8GA1UdIwQYMBaAFJD396jTnyFbmp0n52788T8OR9DfMA8GA1UdEwEB/wQF
    MAMBAf8wDQYJKoZIhvcNAQELBQADggIBAIYxGxpBck1UAtATBrfC+pX4k20cAAyi
    be0jdg8yQLDdGiZdk2aDP2TjZe15t6q6gCtBmaobJyf1qSqmOHi+upOaMIMGgVDn
    kNnPKraQLTutUodDirz73+8hK8SDz3iEiad2LS+lj5xNkh0/rceD6MR8PbpxN0Gd
    iWEhjGsGF0KzWiV+QST7I9kswA73lTicngJRC0fZ5bI/f2PwiF8AOBU/FxXYjgOK
    hTOoBTDofW6bUJiwLgFvfK86xUtq/baUf8pHnUic+PAcjdbjY/WlR4byfR+Fhi0W
    xo9suE2kDp/8flRn0l6YHA0cFUlaESpAT644fu66j2q4dtt/x118kvH9DD5mz/YW
    0xOWz1ihQ9KuRVqMqIJAPWGKmFtk5uu1gJzxVkoix7hA9r/m+0/UxtEUU2Le6swe
    txbLZZwOG1IvT9DSnsLvYzDj0BTuzIALgXCbHGoWAUmZ5tAS/eBKQ6Evoxu3oTWA
    Gm4ieKct63oGOnpn5k4ly0JTd6IarMLu7GYaBXN77FIzR4cYGM4e3r3NVCDXWsK6
    CUfMm4eUf00vezLTdjFeJ0xCB4s6gpQI6naJ4wLkYj8E+32dSxJ4DscIu5TKFIzg
    1z0MVRy09EfLQl42iW5wQ/ukHmYUHrKFc03/3nvrnbv+5wdJvcKA606kjnuKMg58
    3PWpGdKF4WOI
    -----END CERTIFICATE-----
  ca.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQC1P34vPZE0Gp6c
    9g66xfG0oh4wis3H7AlXk9vgEjhBW65HP5F1lLuYThljbTZhEOli2n7Enlo511VK
    W6pE/k7Epxzmxh8q5bDIow3DuSDHK3QWByNTZKi8nwYk/aFT96L9W4p5jwfylH/L
    QUdqUTGwbIA4m98GlECj/d86w1LTjGSDX2kJ1vl7viDVUMlR/gYBIRObO943vV3h
    uJZwlray4FSt5WRyU0l0RzCtlUOWYiHLo/y0f05hjnHK3wq6/GMyzEBpBcUHPd4k
    9XogEofWP2rtuZQiDjOoYnIt1Ztie0WKKsJPU5aeZDLiqw6KCR3p4JmQxh0vWr5y
    97XjSU5E2ezZtl+LbF2jTKrvTN2tV+2ckjTvMuugEQuLaEESaRwHpAezRqvaK+X3
    DaLEcH1Om1mcjQ3N28wYawAfKewTqjRY5iL+Xh7tHq8f413RriYXfjzo47DT6iTi
    uMLEsc8ULSmK1VohOVX0xQF5WVYmip6KoGxY2bNgF1QdT9sSxAfTQLtDNJDQe8Gj
    Br0A3WpovdaPgvHFT0w6wjRtCFup1nTQmu414eny/ETRGy9NGC5dRYnv56Slq+Jt
    PDs6DDQfZT5WnNfOLotCKF1yYLrnk8dAulSq8iBLo0DqdxWbFk33YkyWxT7qNq4p
    w/64t17kutoWbTqAPVCJF2Dua2yc9wIDAQABAoICAAmwy15bPFg81B4wSblSvAmc
    YWDXCwmVZSp5jVf9oWRdMoQ8sdpHiYArLNBUFoQ6E0BlzkFU9h4BlV3UaNYngq6h
    ALqV/TSd80XG8gV08Hu1pw9Gcm0TBLKRDhMMPIPwyZYiPtUhAJvHtM15QAg/Lxjv
    tCtSqin/4zThbf4GU3dcGkOr5kHQbKZhFABTwW/Q1SFaU2IJYWg5h7t50xFR/ZKy
    y9RAX459RYAiDkg5otN3i7cHnYtJAzfUFeFy62/z7pnYsdjrpg0tEaOIPG9ajki2
    O1FaisEHYVuvZ8trkFNDpAQvJRR4s6TkVpQn8S8QLblDePJ0pTrS7zvWYrM0SCrv
    KE/6Jo1h3wk4olvVGoUolLsutzSGDtNeZ+sI9ezL6PiGoB1QRVOnrdZswIboBtsX
    VB8PyYlOUm6iS58ExVkCjmhhv93HJZ9nYTNG7E+D7IURya61e5ST7pmPiLLfRTLn
    sb8fU8wyyJ/0PLznzEyMUoA4YjrsF9o2Dc1c+Frua8Uu+5CYn4Hv4oqfE2Spw3j8
    jgTFPkoVvrqdu4R43+VwWlR5KVjCFPasU4W2DyCUea8g6luJ5nlVxzIkAGGSixbV
    C+L/eSimTLH/AQj50dAVwTdI4zyTNZI3MEbPlk4RcOz/SC9oKmkApfBRHj7QyLqE
    lyBn6keDxKy4uvFsLmYBAoIBAQDk5Rks+Iz+jJUTZi24IAJ5TLkm6D4pkUP33GdX
    ZZeqBL7OOrtxOMC5K+HlGyZ0sBeOw7sV1LEKVxnj2DSKUi/x2nLKvjzMQ3IqciGN
    8/+ng1nAmP/mEuXmNBwSm6Y5uOk4ksE/o43gojEn+Cdsf5JUA+WZT/nKYm8N33lZ
    +IbMRvNqVmQL2ujTjfx5Wh3RWuGRU07L1Qr18ya1bOkdU/5vgb+HvpCVKMIY9wCj
    CwTVYB+v3YM6+vc3kCsyMfk00EBjU2Rf6oasv1mRlc0FmgYH751aTh6Tykr8uOfE
    zogfk2fFU3oqjTXZm2z9NKAMmEkrsSDpmKhkY6yFEThkdvCnAoIBAQDKtf0kZUZJ
    10JEHK+AZ5WaG1pmcwe9IGR7uGMf+8oZ2QGPCEv4U0A+A91xqmsYBRjKA0uN+VMv
    SMvq77X995FQ8RAtfoHvH/hALQTA/KNANDPtqIy0Y+qLTnmiexuMibwh1pTnU4qu
    2iOyUbYfmXnd1VhANdjAyzh+7yFrh/XY3wDzkCdT9EG15ua585BCaCrTKSWXU7e3
    Y5KOFayCrJ1bRuDkll9/L5n/yGe7llqzcaFXBrFU2DP9DLYduVuDeDos+GLL0czO
    joRfniZQ/RbD21x//MwwlxFApoykdgDdFdppKSJsY0ywJV6+tjqjNgBI5yIBGR4g
    gnOOPpqe76sxAoIBAEqQSvw4V43Qc/umzHvviX7EPIhtHVrjJHYIyW1R/e73rsR1
    o3wFldp8bhD5IDTg7DuojThWWfnZV+i+FJd+oHmzxLNA94M+8WDcXwvkEUMbadBw
    xuPHAjdUgFSbebHSB79TJzq4583maAbyMr2IbT2LK28e+2svV6f4RYrGh/rhngfk
    7qBiBnhsB3PspEv/w/1YWxHRa8mlFNYDDYltRDRE2wS4UlcUuO3zALUcMM3li0z5
    5vb+rCvgfgHS/7BxqpfwoYERYB/EEcR4PRp3C0Hoj6TMT++q9XSQM4gME5Hdre88
    +04DRCiIFiAB1aVksmlWQTd3cFuLkLakXm9zw38CggEBALmXOXbzChFc9Zyqrrvf
    GocHeBLISlOLrrPfM1H7EyPrHJQ5wmROxEiC/WGt53MMZ4+8yJXpqZFnEtu8MGGf
    Ifp7WpZsdsXZ/U20ad/O7iBAKzLx2DDoMbrtVEvAbo6TJB3O+nF4eUZxDbGbQiVY
    PM0vISdYpWSOKuF8SprK1fmC4rocRwWEYg0KpD+nkXJbMKo3x+TujwtmLK3Nhi31
    n/QLxqdCTZiCmnomn2KN2+jiphapV/4YHDEYTDyWkgSiNJErsDhvkxWiQevRPb90
    mD0lP2EmsEPka7VHRwjjyRKhiWAyewPFPlcfP8lXygPX0xbsFqPuvTiCdw3Kn4HY
    aGECggEAPsxBUuCDYHOcbkuJVGHIJvoWFLhafBGnE9NglhikGfxjxCel8+I2GeWY
    XQY2aOeuNiuWlo/qLjkHYGysRVTAovhkWD7wZaw/Xkmvz6p8IUzJ6sCk4LgOPm0r
    QC+xG6QnaYfp1CULddlLTYlIYaqVDy4q+ZpUQo2Of2adWjF0o67zjuR0mc6ATAzq
    JKv27DsyV8ecFSuZHz7Vl4tz8DBJNaBWY4fcxiztuJkmUUq75ZjMEhEHxmJ1vyyL
    As7OdTYx2wBDZc+MUYWoi4U412IsotnVSPp/ZqYSc7VoC9R87nZ+ShB7KxZPEhEB
    ZP4IyayfKB9x3AeKhMK4YaUwli4Y/g==
    -----END PRIVATE KEY-----
  ca.srl: |
    1255908D0955BBFDD1BE2D90E5AA809737248C88
  server.cnf: |-
    [req]
    prompt = no
    default_md = sha256
    req_extensions = req_ext
    distinguished_name = dn

    [dn]
    C = US
    ST = FL
    L = Hialeah
    O = New Window System
    CN = api-qbwc-zoho.newwindowsystem.net

    [req_ext]
    subjectAltName = @alt_names

    [alt_names]
    DNS.1 = api-qbwc-zoho.newwindowsystem.net
    DNS.2 = wms.newwindowsystem.net
  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE7zCCAtegAwIBAgIUElWQjQlVu/3Rvi2Q5aqAlzckjIgwDQYJKoZIhvcNAQEL
    BQAwYjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkZMMRAwDgYDVQQHDAdIaWFsZWFo
    MRowGAYDVQQKDBFOZXcgV2luZG93IFN5c3RlbTEYMBYGA1UEAwwPTldTLUludGVy
    bmFsLUNBMB4XDTI1MTIxNTIwNDgwN1oXDTI4MDMxOTIwNDgwN1owdDELMAkGA1UE
    BhMCVVMxCzAJBgNVBAgMAkZMMRAwDgYDVQQHDAdIaWFsZWFoMRowGAYDVQQKDBFO
    ZXcgV2luZG93IFN5c3RlbTEqMCgGA1UEAwwhYXBpLXFid2Mtem9oby5uZXd3aW5k
    b3dzeXN0ZW0ubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsghY
    TH+7ax5NdNtt/UhCo9bFC/Qr+5JOAC+noAVMAsPOi0NwQhP07oQOswN29gOEywuF
    BHWoPReJaJhe9uTi/bVDslie/we5tqF/KCZNAxDF5Gdkt8q5Sw7suhYrVZd3NiDj
    bn/SXgLSnLbroplczmF3j0ZJLlN3sziZXUB+cunJwnbgmStnC+92WIlgv3HvYTUQ
    80YUyaNxycD8E1JmQWORx4UgBoeawz/Olqlyrdr6DQ4QCwBnvjHEpDRulvxVZPDL
    tcURSjKjSeryE9l4SPGJatXmJ6acglH2HOXcFim/3eadPgyfO91JcYYvi1aes3E7
    qRD6IfYpbia6eUWx4wIDAQABo4GKMIGHMEUGA1UdEQQ+MDyCIWFwaS1xYndjLXpv
    aG8ubmV3d2luZG93c3lzdGVtLm5ldIIXd21zLm5ld3dpbmRvd3N5c3RlbS5uZXQw
    HQYDVR0OBBYEFEem5xNpIdiS1zW+YgQOPqBqK0sMMB8GA1UdIwQYMBaAFJD396jT
    nyFbmp0n52788T8OR9DfMA0GCSqGSIb3DQEBCwUAA4ICAQAVHxIfVxg3gR15UDzp
    YBmXGxuBYFunFicXvlLJyApNho1tG+1reWTyKZproGZBxZQqsWg8FhfeDY2XBYVL
    A+csXSlVvQrY7ne2zTY3/6m8JbW/vuFgCakEOGZSy+s/Bb4pGHLj3dEce5Iv31eQ
    3CBMqVECiTUj9U+4x4x+KHvKO8Jvlawv+rx0Vx8TdgTxF3ZVM6SPOn0WSc9rJOqi
    6bC3UHxcfSQ30iaPqG91p8UQwi6hm60ltsik+VxdDjsonGmhCSVjCsIaRbYFlPbA
    cK8uONKbNfcEx6a1BkqNjMDnvydFQukJ/61lmQcjNiwGkpTS0FWymDunRTCkHvhp
    kTy/CdT05z4rU3ENUjXAEraLzmr2Fcr1uw2sJqypoKvu/SYVR8bX+KDbrsugBTEw
    3tEpOtAPR4pYzktIsA3nzpgDp07DLJuBzXRX8v6XoBt7iiHqLU486qKh4zuvNVi4
    74XV/MkCL0+mClIzinOTTln8oSIYSygVVySkHQiyvXMSxV2Dq19Eli6SSS9vnjFI
    jgK4n5sKd4JgaoJ+PzGlLj8po5EYY5sKxzvsNypoZH3n6j7nc61jcwAlY+t0RWiK
    wg07LaEnfR1DFodvBt2R3hXPBJlxoaBQqYV2DscOO2qaNkGX1dsD3WB5gkPGFawi
    PMORARC8F1cCwHDDd5nH0GVMfQ==
    -----END CERTIFICATE-----
  server.csr: |
    -----BEGIN CERTIFICATE REQUEST-----
    MIIDETCCAfkCAQAwdDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkZMMRAwDgYDVQQH
    DAdIaWFsZWFoMRowGAYDVQQKDBFOZXcgV2luZG93IFN5c3RlbTEqMCgGA1UEAwwh
    YXBpLXFid2Mtem9oby5uZXd3aW5kb3dzeXN0ZW0ubmV0MIIBIjANBgkqhkiG9w0B
    AQEFAAOCAQ8AMIIBCgKCAQEAsghYTH+7ax5NdNtt/UhCo9bFC/Qr+5JOAC+noAVM
    AsPOi0NwQhP07oQOswN29gOEywuFBHWoPReJaJhe9uTi/bVDslie/we5tqF/KCZN
    AxDF5Gdkt8q5Sw7suhYrVZd3NiDjbn/SXgLSnLbroplczmF3j0ZJLlN3sziZXUB+
    cunJwnbgmStnC+92WIlgv3HvYTUQ80YUyaNxycD8E1JmQWORx4UgBoeawz/Olqly
    rdr6DQ4QCwBnvjHEpDRulvxVZPDLtcURSjKjSeryE9l4SPGJatXmJ6acglH2HOXc
    Fim/3eadPgyfO91JcYYvi1aes3E7qRD6IfYpbia6eUWx4wIDAQABoFgwVgYJKoZI
    hvcNAQkOMUkwRzBFBgNVHREEPjA8giFhcGktcWJ3Yy16b2hvLm5ld3dpbmRvd3N5
    c3RlbS5uZXSCF3dtcy5uZXd3aW5kb3dzeXN0ZW0ubmV0MA0GCSqGSIb3DQEBCwUA
    A4IBAQBLO3MaiiWyAjl4TgumjmJPky3DMhOEuPE62Q+kn03Iie5RBAyDdIcDJU4f
    oDIx1zIq6TkXzXQu6edo8d25aDMsL1u+P757XQBZ2GwxvWU7nyXUedIVGwV6fo64
    IdmsAJTlnIdVuOaWsea8xo+wFXj2+6istXb6XajwSzNOyYcX8Kn+qT9bXB1VZh7Z
    5tbMIoMDpcAIEnKiukmL1RrcVLrxtUffpYxXy04J+32NaOA5lpqvdEEbrYZGu836
    OV8CSUlgG2NYlMD2ae6shYVflTwufEj2fQaHH/j29fC2/TH8StbJcV4pJAq50Den
    qL52kfNV++LC1TZfSUWR8WQEcQvQ
    -----END CERTIFICATE REQUEST-----
  server.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyCFhMf7trHk10
    2239SEKj1sUL9Cv7kk4AL6egBUwCw86LQ3BCE/TuhA6zA3b2A4TLC4UEdag9F4lo
    mF725OL9tUOyWJ7/B7m2oX8oJk0DEMXkZ2S3yrlLDuy6FitVl3c2IONuf9JeAtKc
    tuuimVzOYXePRkkuU3ezOJldQH5y6cnCduCZK2cL73ZYiWC/ce9hNRDzRhTJo3HJ
    wPwTUmZBY5HHhSAGh5rDP86WqXKt2voNDhALAGe+McSkNG6W/FVk8Mu1xRFKMqNJ
    6vIT2XhI8Ylq1eYnppyCUfYc5dwWKb/d5p0+DJ873Ulxhi+LVp6zcTupEPoh9ilu
    Jrp5RbHjAgMBAAECggEAKiersMF2AVE1ifwDOTwI+355PfFdEL591bFzAYL/kpAG
    shcP17WeA3QlfuHNI0eGBAYAQyQQ6BZQpQGfStq7nNN06h/t1flgUgw/baRUC+vG
    z+RjhtlrsoggKZfiPuwUgC6da6a8iyIj+JOfi+rAfOW7R6Oe5GdDKp62QcxppI+t
    vtvuJyzQDHvEt8cSDFDCkDGvhG9ZHsHzUscN9Bq0ARj1nfTfKHaoxNzUIpCJ2Ym0
    YylvCZHtKAMWtRMYzTKOIlG29AZTDaGS4VPs73y+HSrR1UarfpcGPuTvViNxixus
    JilK+QPzhzFp41VKdjx7ebjRNaI8MhGUxtFUC7i4gQKBgQDiQgRzgA5/6FUKgepu
    1YNkg9VclvwBZjC4mOeiAPDfdvBKAehFFUOeJFkDeal76cGz6x5b2YFHVAPqXntP
    v0ENj8gxUobmkToz5oGodPUftMrYVlgO4mRO1Kce74r7k6dWylwvJPmIipNkyxW9
    LvC6/QBYnGJhsRfhgtQw73or4QKBgQDJb3Xfs2jeJLHtFUelWFDy6XINzhqruEIF
    48TZvT7qAcPn4FzckfL3Ye90UPRG+RgnRNjNhCFpbm5o73rtzxCUuiOZmaD3SSTF
    QbYPZWOLUyuwty0ocqZtH3oazAsA/+6tA3tdulVuNOLNYInjcGBzRBRB7sQC6Ebs
    fIbq2mL2QwKBgQCR3pYYENtIQ3VwTMnjouwPBZ+tDfpyvHt0x7+uhoTEzV2lmQ0y
    XL83WZ+5ydom9VHYuSDdfqEGZ3gOxdMiWt+J6sTaZ6ZpSAAKLfYxsRXH1ztftmsX
    TYX1/Mux+iXUhCFCpzw/eMsX6J+WQAhH69dv9mUeu9QBv7bxwPMkiYBugQKBgE2Q
    0f72AuenkawNia0tuN4Q7o5KUxLUvPevoVmG+fb5/woG5zs4KCsCV0ae9bFusdJN
    PH7G5mbG01UtAlUYavYaRyMaeVU/oR0kFIsRK6e2uxgtMQJmQ5e5izdOYt5brviI
    YrTQz5zEWKFlDzO5TiqUiIhq/Kdx8f2WZg2BUqIpAoGAeGPtfR3Qpu7m+9bIIdb4
    JyY3ftcrqGoCMqb9nHTeWxUK9/NvoxDLr3qZPMUATj36hd87xoTqR0ZIf53neK3Q
    iGIuyLR/+vtvTXiq17KA8jE/vxDBJcOKUYKegtr0PpsJIOHt8vmS5/zdcKxynqtU
    DgZjUaIJqkBSFp6l71g3rpk=
    -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: nginx-server
  name: nginx-server-cm1
