apiVersion: v1
data:
  init.sql: "DO $$ \nBEGIN\n   IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'api_qbwc_zoho_dev_db') THEN\n      CREATE DATABASE api_qbwc_zoho_dev_db;\n   END IF;\n   IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'api_qbwc_zoho_qa_db') THEN\n      CREATE DATABASE api_qbwc_zoho_qa_db;\n   END IF;\n   IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'api_qbwc_zoho_prod_db') THEN\n      CREATE DATABASE api_qbwc_zoho_prod_db;\n   END IF;\n   IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'api_qbwc_zoho_envqa_db') THEN\n      CREATE DATABASE api_qbwc_zoho_envqa_db;\n   END IF;\n   IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'api_qbwc_zoho_envprod_db') THEN\n      CREATE DATABASE api_qbwc_zoho_envprod_db;\n   END IF;\n\nEND\n$$;\n"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres-cm1
