apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml -o .\k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: react-app
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml -o .\k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: react-app
    spec:
      containers:
        - image: react-app
          name: react-app
          volumeMounts:
            - mountPath: /app/build
              name: react-app-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: react-app-cm0
          name: react-app-cm0
