# Generated by Django 5.0.6 on 2024-06-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('zoho_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('zoho_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('zoho_org_id', models.CharField(blank=True, max_length=255, null=True)),
                ('zoho_redirect_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('zoho_refresh_time', models.DurationField(blank=True, null=True)),
                ('zoho_refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('zoho_connection_configured', models.BooleanField(default=False)),
                ('qb_username', models.CharField(blank=True, max_length=255, null=True)),
                ('qb_password', models.CharField(blank=True, max_length=255, null=True)),
                ('qb_owner_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]