# Generated by Django 5.0.6 on 2024-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='zoho_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]