# Generated by Django 5.0.6 on 2024-07-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    
    run_before = [
        ('admin', '__first__'),
    ]

    dependencies = [
        ('api_zoho', '0002_appconfig_zoho_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]