# Generated by Django 5.0.6 on 2024-07-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0004_alter_loginuser_options_alter_loginuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='loginuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]