# Generated by Django 5.0.6 on 2024-07-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0005_alter_loginuser_options_alter_loginuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoLoading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zoho_module', models.CharField(blank=True, max_length=255)),
                ('zoho_record_status', models.CharField(blank=True, max_length=255)),
                ('zoho_record_message', models.TextField(blank=True)),
                ('zoho_record_created', models.DateField(blank=True)),
                ('zoho_record_updated', models.DateTimeField(blank=True)),
            ],
        ),
    ]
