# Generated by Django 5.0.6 on 2024-08-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0006_zoholoading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTrackingLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_user', models.CharField(blank=True, max_length=255)),
                ('log_action', models.CharField(blank=True, max_length=255)),
                ('log_pc_ip', models.CharField(blank=True, max_length=255)),
                ('log_message', models.TextField(blank=True)),
                ('log_created', models.DateTimeField(blank=True)),
                ('log_modified', models.DateTimeField(blank=True)),
            ],
        ),
    ]
