# Generated by Django 5.0.6 on 2024-08-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0008_notification_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_user',
        ),
    ]
