# Generated by Django 5.0.6 on 2024-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0009_remove_notification_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_module',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
