# Generated by Django 5.0.6 on 2024-06-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QbItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('list_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
