# Generated by Django 5.0.6 on 2024-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quickbook_soap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QbCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('list_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
