# Generated by Django 5.0.6 on 2024-06-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quickbook_soap', '0002_qbcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='qbcustomer',
            name='matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qbitem',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
