# Generated by Django 5.0.6 on 2024-06-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quickbook_soap', '0003_qbcustomer_matched_qbitem_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='list_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qbitem',
            name='list_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qbitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
