# Generated by Django 5.0.6 on 2024-07-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quickbook_soap', '0004_alter_qbcustomer_email_alter_qbcustomer_list_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qbcustomer',
            name='never_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qbitem',
            name='never_match',
            field=models.BooleanField(default=False),
        ),
    ]
