# Generated by Django 5.0.6 on 2024-07-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quickbook_soap', '0005_qbcustomer_never_match_qbitem_never_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='QbLoading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qb_module', models.CharField(blank=True, max_length=255)),
                ('qb_record_status', models.CharField(blank=True, max_length=255)),
                ('qb_record_message', models.TextField(blank=True)),
                ('qb_record_created', models.DateField(blank=True)),
                ('qb_record_updated', models.DateTimeField(blank=True)),
            ],
        ),
    ]
