# Generated by Django 5.0.6 on 2025-09-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_sales_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='zohofullsalesorder',
            new_name='api_zoho_sa_date_0f001e_idx',
            old_name='zfsorder_date_idx',
        ),
        migrations.RenameIndex(
            model_name='zohofullsalesorder',
            new_name='api_zoho_sa_status_2e709f_idx',
            old_name='zfsorder_status_idx',
        ),
        migrations.RenameIndex(
            model_name='zohofullsalesorder',
            new_name='api_zoho_sa_custome_0211ed_idx',
            old_name='zfsorder_customer_idx',
        ),
    ]
