# Generated by Django 5.0.6 on 2024-06-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_invoices', '0003_zohofullinvoice_delete_zohoinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohofullinvoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
