# Generated by Django 5.0.6 on 2024-06-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_invoices', '0004_alter_zohofullinvoice_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zohofullinvoice',
            options={'verbose_name': 'Zoho Full Invoice', 'verbose_name_plural': 'Zoho Full Invoices'},
        ),
    ]
