# Generated by Django 5.0.6 on 2024-06-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_invoices', '0007_alter_zohofullinvoice_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohofullinvoice',
            name='customer_unmatched',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='zohofullinvoice',
            name='items_unmatched',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
