# Generated by Django 5.0.6 on 2024-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_invoices', '0009_remove_zohofullinvoice_ach_payment_initiated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohofullinvoice',
            name='force_to_sync',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
