# Generated by Django 5.0.6 on 2024-07-09 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_invoices', '0010_zohofullinvoice_force_to_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohofullinvoice',
            name='last_sync_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 7, 9)),
        ),
        migrations.AddField(
            model_name='zohofullinvoice',
            name='number_of_times_synced',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
