# Generated by Django 5.0.6 on 2024-07-09 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_invoices', '0011_zohofullinvoice_last_sync_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohofullinvoice',
            name='last_sync_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
