# Generated by Django 5.0.6 on 2024-07-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_invoices', '0012_alter_zohofullinvoice_last_sync_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohofullinvoice',
            name='all_customer_matched',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='zohofullinvoice',
            name='all_items_matched',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
