# Generated by Django 5.0.6 on 2024-08-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho_invoices', '0013_zohofullinvoice_all_customer_matched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohofullinvoice',
            name='qb_customer_list_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
